#ddev-generated
hooks:
  pre-start:
    # If Playwright is enabled, make sure we get any changes.
    - exec-host: |
        ([[ -f .ddev/web-build/Dockerfile.playwright ]] && \
          cp .ddev/web-build/disabled.Dockerfile.playwright .ddev/web-build/Dockerfile.playwright && \
          cp .ddev/.disabled-services/docker-compose.playwright-vnc.yaml .ddev/) || true
    - exec-host: |
        if [[ -f .ddev/web-build/Dockerfile.playwright ]]
        then
          rm -rf .ddev/web-build/playwright
          cp -r test/playwright .ddev/web-build/
        fi
web_environment:
  - DISPLAY=:99.0
# We add the sleep so this doesn't error out when not using playwright.
web_extra_daemons:
  - name: "xvfb"
    command: "/usr/local/bin/start-xvfb.sh || sleep infinity"
    directory: /var/www/html
  - name: "vnc"
    command: "/usr/local/bin/start-vnc.sh || sleep infinity"
    directory: /var/www/html
  - name: "novnc"
    command: "/usr/local/bin/start-novnc.sh || sleep infinity"
    directory: /var/www/html
web_extra_exposed_ports:
  - name: playwright
    container_port: 9323
    http_port: 8323
    https_port: 9324
  - name: novnc
    container_port: 7900
    http_port: 7910
    https_port: 7900
