#!/bin/bash
#ddev-generated

PLAYWRIGHT_TEST_DIR="${PLAYWRIGHT_TEST_DIR:-test/playwright}"
if [ ! -f "$PLAYWRIGHT_TEST_DIR/package.json" ]; then
  echo "No playwright installation exists at $PLAYWRIGHT_TEST_DIR."
  # https://github.com/microsoft/playwright/issues/11843
  echo "Playwright does not support a non-interactive setup and must be done manually."
  echo ""
  echo "Run the following to use npm:"
  echo "  ddev playwright-init
  echo ""
  echo "Run the following to use yarn instead:"
  echo "  ddev playwright-init --pm yarn"
  echo ""
  echo "Answer \"no\" when it asks to install browsers and operating system dependencies,"
  echo "as those will be erased when ddev restarts."
  echo ""
  echo "As well, add ignoreHTTPSErrors: true to playwright.config.ts."
  echo ""
  echo "See https://playwright.dev/docs/intro for more details."
  echo ""
  echo "When done, run: ddev install-playwright"
  exit 1
fi

# ddev errors out on subsequent builds if we symlink these files. Instead, we
# copy them each time.
echo "Preparing web service with playwright dependencies..."
cp .ddev/web-build/disabled.Dockerfile.playwright .ddev/web-build/Dockerfile.playwright
echo "Please run the following on your host to apply the change:"
echo ""
echo "  ddev restart"
echo ""
exit 0
