name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
    - uses: ddev/github-action-add-on-test@ce27c56d7bea44342a704c26824a147b3f148732 # v2
      with:
        ddev_version: ${{ matrix.ddev_version }}
        addon_repository: ${{ github.repository }}
        addon_ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        debug_enabled: ${{ github.event.inputs.debug_enabled || false }}
