name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

defaults:
  run:
    shell: bash

env:
  NIGHTLY_DDEV_PR_URL: "https://nightly.link/ddev/ddev/actions/runs/1720215802/ddev-linux-amd64.zip"

jobs:
  tests:
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        ddev_version: [stable, HEAD]
#        ddev_version: [stable, edge, HEAD, PR]
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Environment setup
      run: |
        brew update && brew upgrade
        brew install mkcert
        mkcert -install
        git submodule init
        git submodule update

    - name: Use ddev stable
      if: matrix.ddev_version == 'stable'
      run: brew install ddev/ddev/ddev

    - name: Use ddev edge
      if: matrix.ddev_version == 'edge'
      run: brew install ddev/ddev-edge/ddev

    - name: Use ddev HEAD
      if: matrix.ddev_version == 'HEAD'
      run: brew install --HEAD ddev/ddev/ddev

    - name: Use ddev PR
      if: matrix.ddev_version == 'PR'
      run: |
        curl -sSL -o ddev_linux.zip ${NIGHTLY_DDEV_PR_URL}
        unzip ddev_linux.zip
        mv ddev /usr/local/bin/ddev && chmod +x /usr/local/bin/ddev

    - name: Download docker images
      run: mkdir junk && pushd junk && ddev config --auto && ddev debug download-images >/dev/null

    - name: tests
      run: ./tests/bats/bin/bats -t tests

    # keepalive-workflow adds a dummy commit if there's no other action here, keeps
    # GitHub from turning off tests after 60 days
    - uses: gautamkrishnar/keepalive-workflow@3eb47f21355191080dca0f7662d45c192d2ef64d # v2
      if: matrix.ddev_version == 'stable'
